# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 185)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.table_1_code_from_job_QGroupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.table_1_code_from_job_QGroupBox.setGeometry(QtCore.QRect(30, 30, 201, 131))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.table_1_code_from_job_QGroupBox.setFont(font)
        self.table_1_code_from_job_QGroupBox.setObjectName("table_1_code_from_job_QGroupBox")
        self.table_1_button_create_file = QtWidgets.QPushButton(parent=self.table_1_code_from_job_QGroupBox)
        self.table_1_button_create_file.setGeometry(QtCore.QRect(20, 60, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.table_1_button_create_file.setFont(font)
        self.table_1_button_create_file.setObjectName("table_1_button_create_file")
        self.table_2_code_from_defect_groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.table_2_code_from_defect_groupBox.setGeometry(QtCore.QRect(270, 30, 201, 131))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.table_2_code_from_defect_groupBox.setFont(font)
        self.table_2_code_from_defect_groupBox.setObjectName("table_2_code_from_defect_groupBox")
        self.table_2_button_create_file = QtWidgets.QPushButton(parent=self.table_2_code_from_defect_groupBox)
        self.table_2_button_create_file.setGeometry(QtCore.QRect(20, 60, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.table_2_button_create_file.setFont(font)
        self.table_2_button_create_file.setObjectName("table_2_button_create_file")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Помощник Меридиан"))
        self.table_1_code_from_job_QGroupBox.setTitle(_translate("MainWindow", "Коды из Job"))
        self.table_1_button_create_file.setText(_translate("MainWindow", "Создать txt файл"))
        self.table_2_code_from_defect_groupBox.setTitle(_translate("MainWindow", "Коды из брака"))
        self.table_2_button_create_file.setText(_translate("MainWindow", "Создать txt файл"))


if __name__ == '__main__':
    import work_to_files
    import sys


    def open_file_dialog_job():
        file_path, _ = QtWidgets.QFileDialog.getOpenFileName()
        if file_path != "":
            wtf = work_to_files.Meridian()
            wtf.file = file_path
            wtf.file_job()


    def open_file_dialog_defect():
        file_path, _ = QtWidgets.QFileDialog.getOpenFileName()
        if file_path != "":
            wtf = work_to_files.Meridian()
            wtf.file = file_path
            wtf.file_defect()


    # Настройка отображения ui-интерфейса.
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)

    # Привязка кнопок к функциям.
    ui.table_1_button_create_file.clicked.connect(open_file_dialog_job)
    ui.table_2_button_create_file.clicked.connect(open_file_dialog_defect)

    MainWindow.show()
    sys.exit(app.exec())